/**
 * JsonToStringBuilder.java
 * Project EclipseToStringBuilderForJson
 * Licensed under MIT.
 */
package com.github.djaganathan.opensource.eclipse.util;

import java.util.Arrays;
import java.util.Collection;
import java.util.Map;
import java.util.Objects;

/**
 * This is a Eclipse Custom toString Builder class, which help to generate toString method to return a JSON formatted string.
 * 
 * References:-
 * http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fref-tostring-styles.htm
 * https://gist.github.com/ulisseslima/7de22e06f85846594a1bd6ffff79b0da
 * http://stackoverflow.com/questions/41967627/how-to-create-string-format-template-to-generate-json-for-eclipse-autogenerated
 */
public class JsonToStringBuilder {

    private StringBuilder aJson = new StringBuilder();

    public JsonToStringBuilder(Object o) {
        super();
        aJson.ensureCapacity(256);
    }

    /**
     * This append method prepares the a Key and Value element in the JSON for input of fieldName
     * and fieldValue
     * @param fieldName
     * @param fieldValue
     * @return this
     */
    public JsonToStringBuilder append(final String fieldName, final Object fieldValue) {
        aJson.append(aJson.length() == 0 ? "" : ",").append("\"").append(fieldName).append("\": ").append(new ValueSerializer(fieldValue).serialize());
        return this;
    }


    /**
     * Gives to a String in the JSON format
     * @return String - In the format of Json
     */
    public String build() {
        return toString();
    }

    /**
     * Builds a String representation of the object
     */
    @Override
    public String toString() {
        return "{" + aJson.toString() + "}";
    }

    class ValueSerializer {

        Object fieldValue;

        ValueSerializer(Object iFieldValue) {
            fieldValue = iFieldValue;
        }

        public StringBuilder serialize() {
            StringBuilder aValue = new StringBuilder();
            if (fieldValue == null) {
                aValue.append("null");
            } else if (fieldValue instanceof Number) {
                aValue.append(fieldValue);
            } else if (fieldValue instanceof CharSequence || fieldValue instanceof Enum) {
                aValue.append("\"").append(fieldValue).append("\"");
            } else if (fieldValue instanceof Collection<?> || fieldValue instanceof Object[]) {
                aValue.append(new LinearCollection(fieldValue).serialize());
            } else if (fieldValue instanceof Map<?, ?>) {
                aValue.append(new MappedCollection(fieldValue).serialize());
            } else {
                aValue.append(String.valueOf(fieldValue));
            }
            return aValue;
        }
    }

    class LinearCollection {
        Collection<?> items;
        public LinearCollection(Object objArray) {
            if (objArray == null) {
                items = null;
            } else if (objArray instanceof Object[]) {
                items = Arrays.asList((Object[]) objArray);
            } else if (objArray instanceof Collection<?>) {
                this.items = (Collection<?>) objArray;
            } else {
                items = null;
            }
        }

        public StringBuilder serialize() {
            if (Objects.isNull(items)) {
                return null;
            }
            StringBuilder aStr = new StringBuilder();
            if (items.isEmpty()) {
                aStr.append("[]");
                return aStr;
            }
            aStr.append("[");
            for (Object item : items) {
                aStr.append(new ValueSerializer(item).serialize());
                aStr.append(",");
            }
            aStr.deleteCharAt(aStr.length() - 1);
            aStr.append("]");
            return aStr;
        }
    }

    class MappedCollection {

        Map<?, ?> aMap;

        public MappedCollection(Object iMap) {
            if(iMap ==null) {
                this.aMap = null;
            }else if(iMap instanceof Map<?,?> ) {
                this.aMap = (Map<?, ?>) iMap;
            } else {
                this.aMap = null;
            }
        }

        public StringBuilder serialize() {
            if (Objects.isNull(aMap)) {
                return null;
            }
            StringBuilder aStr = new StringBuilder();
            if (aMap.entrySet().isEmpty()) {
                aStr.append("{}");
                return aStr;
            }
            aStr.append("{");
            for (Map.Entry<?, ?> aEntry : aMap.entrySet()) {
                aStr.append("\"").append(aEntry.getKey()).append("\": ");
                aStr.append(new ValueSerializer(aEntry.getValue()).serialize());
                aStr.append(",");
            }
            aStr.deleteCharAt(aStr.length() - 1);
            aStr.append("}");
            return aStr;
        }
    }
}

